version: '3.8'
services:
  apis:
    image: aimelyse/power_cash_apis:latest
    tty: true
    stdin_open: true
    build: 
      context: power_cash
      dockerfile: Dockerfile
  frontend:
    image:  aimelyse/power_cash_frontend:latest
    tty: true
    stdin_open: true
    build: 
      context: power_cash
      dockerfile: Dockerfile
  db:
    image: aimelyse/power_cash_db:latest
    tty: true
    stdin_open: true
    build:
      context:  apis
      dockerfile: db.Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  nginx:
    image: "aimelyse/nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
volumes:
  apis:
  frontend:
  db: